title: Asapac's blog
author: Asapac
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Thank you for visiting!
  This is my blog on GitHub pages.
# social links
github_username:  Asapac # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
